/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BattlesRouteImport } from './routes/battles'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LendingRouteImport } from './routes/lending'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as MarketIndexRouteImport } from './routes/market/index'
import { Route as MarketListingIdRouteImport } from './routes/market/$listingId'
import { Route as PacksIndexRouteImport } from './routes/packs/index'
import { Route as PacksPackIdRouteImport } from './routes/packs/$packId'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as UAddressAddressRouteImport } from './routes/u/address/$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesRoute = BattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LendingRoute = LendingRouteImport.update({
  id: '/lending',
  path: '/lending',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketListingIdRoute = MarketListingIdRouteImport.update({
  id: '/market/$listingId',
  path: '/market/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksIndexRoute = PacksIndexRouteImport.update({
  id: '/packs/',
  path: '/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksPackIdRoute = PacksPackIdRouteImport.update({
  id: '/packs/$packId',
  path: '/packs/$packId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const UAddressAddressRoute = UAddressAddressRouteImport.update({
  id: '/u/address/$address',
  path: '/u/address/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/battles': typeof BattlesRoute
  '/collection': typeof CollectionRoute
  '/docs': typeof DocsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lending': typeof LendingRoute
  '/privacy': typeof PrivacyRoute
  '/redeem': typeof RedeemRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trading': typeof TradingRoute
  '/market/$listingId': typeof MarketListingIdRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/u/$username': typeof UUsernameRoute
  '/market/': typeof MarketIndexRoute
  '/packs/': typeof PacksIndexRoute
  '/u/address/$address': typeof UAddressAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/battles': typeof BattlesRoute
  '/collection': typeof CollectionRoute
  '/docs': typeof DocsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lending': typeof LendingRoute
  '/privacy': typeof PrivacyRoute
  '/redeem': typeof RedeemRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trading': typeof TradingRoute
  '/market/$listingId': typeof MarketListingIdRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/u/$username': typeof UUsernameRoute
  '/market': typeof MarketIndexRoute
  '/packs': typeof PacksIndexRoute
  '/u/address/$address': typeof UAddressAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/battles': typeof BattlesRoute
  '/collection': typeof CollectionRoute
  '/docs': typeof DocsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lending': typeof LendingRoute
  '/privacy': typeof PrivacyRoute
  '/redeem': typeof RedeemRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/trading': typeof TradingRoute
  '/market/$listingId': typeof MarketListingIdRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/u/$username': typeof UUsernameRoute
  '/market/': typeof MarketIndexRoute
  '/packs/': typeof PacksIndexRoute
  '/u/address/$address': typeof UAddressAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/battles'
    | '/collection'
    | '/docs'
    | '/leaderboard'
    | '/lending'
    | '/privacy'
    | '/redeem'
    | '/support'
    | '/terms'
    | '/trading'
    | '/market/$listingId'
    | '/packs/$packId'
    | '/u/$username'
    | '/market/'
    | '/packs/'
    | '/u/address/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/battles'
    | '/collection'
    | '/docs'
    | '/leaderboard'
    | '/lending'
    | '/privacy'
    | '/redeem'
    | '/support'
    | '/terms'
    | '/trading'
    | '/market/$listingId'
    | '/packs/$packId'
    | '/u/$username'
    | '/market'
    | '/packs'
    | '/u/address/$address'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/battles'
    | '/collection'
    | '/docs'
    | '/leaderboard'
    | '/lending'
    | '/privacy'
    | '/redeem'
    | '/support'
    | '/terms'
    | '/trading'
    | '/market/$listingId'
    | '/packs/$packId'
    | '/u/$username'
    | '/market/'
    | '/packs/'
    | '/u/address/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BattlesRoute: typeof BattlesRoute
  CollectionRoute: typeof CollectionRoute
  DocsRoute: typeof DocsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LendingRoute: typeof LendingRoute
  PrivacyRoute: typeof PrivacyRoute
  RedeemRoute: typeof RedeemRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TradingRoute: typeof TradingRoute
  MarketListingIdRoute: typeof MarketListingIdRoute
  PacksPackIdRoute: typeof PacksPackIdRoute
  UUsernameRoute: typeof UUsernameRoute
  MarketIndexRoute: typeof MarketIndexRoute
  PacksIndexRoute: typeof PacksIndexRoute
  UAddressAddressRoute: typeof UAddressAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles': {
      id: '/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof BattlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lending': {
      id: '/lending'
      path: '/lending'
      fullPath: '/lending'
      preLoaderRoute: typeof LendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$listingId': {
      id: '/market/$listingId'
      path: '/market/$listingId'
      fullPath: '/market/$listingId'
      preLoaderRoute: typeof MarketListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/': {
      id: '/packs/'
      path: '/packs'
      fullPath: '/packs/'
      preLoaderRoute: typeof PacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$packId': {
      id: '/packs/$packId'
      path: '/packs/$packId'
      fullPath: '/packs/$packId'
      preLoaderRoute: typeof PacksPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/address/$address': {
      id: '/u/address/$address'
      path: '/u/address/$address'
      fullPath: '/u/address/$address'
      preLoaderRoute: typeof UAddressAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BattlesRoute: BattlesRoute,
  CollectionRoute: CollectionRoute,
  DocsRoute: DocsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LendingRoute: LendingRoute,
  PrivacyRoute: PrivacyRoute,
  RedeemRoute: RedeemRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TradingRoute: TradingRoute,
  MarketListingIdRoute: MarketListingIdRoute,
  PacksPackIdRoute: PacksPackIdRoute,
  UUsernameRoute: UUsernameRoute,
  MarketIndexRoute: MarketIndexRoute,
  PacksIndexRoute: PacksIndexRoute,
  UAddressAddressRoute: UAddressAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
